language: python
cache:
  - apt
  - pip
python:
  - "2.7"
  - "3.6"
before_install:
  - sudo apt-get install libicu-dev -y
install:
  - pip install pyicu cchardet
  - pip install -e .
  - pip install nose coveralls
script:
  - nosetests --with-coverage --cover-package=normality
after_success:
  - coveralls
