language: python
cache:
  - apt
  - pip
python:
  - "2.7"
  - "3.6"
addons:
  apt:
    packages:
      - libicu52
install:
  - pip install pyicu cchardet
  - pip install -e .
  - pip install nose coveralls
script:
  - nosetests --with-coverage --cover-package=normality
after_success:
  - coveralls
